name: Build macOS App (Intel & Apple Silicon)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: macos-12
            artifact: Jeffern影视平台-x86_64
          - arch: arm64
            runner: macos-14
            artifact: Jeffern影视平台-arm64

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller webview

      - name: 打包应用
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "Jeffern影视平台" mac-web.py

      - name: 上传打包产物
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: dist/*
