name: Build macOS App (Universal2)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      APP_NAME: Jeffern影视平台
      PY_FILE: mac-web.py

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pywebview

      - name: 清理旧的打包缓存
        run: |
          rm -rf build dist __pycache__ *.spec

      - name: 打包 Universal2 应用
        run: |
          pyinstaller --clean --noconfirm --onefile --windowed \
            --name "${APP_NAME}-universal2" \
            --target-arch universal2 \
            --hidden-import pywebview \
            "${PY_FILE}"

      - name: 打包产物压缩（包含所有文件）
        run: |
          mkdir -p dist_upload
          cd dist
          zip -r "../dist_upload/${APP_NAME}-universal2.zip" "${APP_NAME}-universal2"*
          cd ..

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.APP_NAME }}-universal2"
          path: dist_upload/*.zip

  release:
    needs: build-macos
    runs-on: ubuntu-latest
    steps:
      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        with:
          path: all_dist

      - name: 展示产物
        run: ls -R all_dist

      - name: 上传到 GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: all_dist/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
