name: Build macOS App (Intel & Apple Silicon)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    env:
      APP_NAME: Jeffern影视平台
      PY_FILE: mac-web.py

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: 打包应用
        run: |
          export ARCH="${{ matrix.arch }}"
          pyinstaller --noconfirm --onefile --windowed --name "${APP_NAME}-${ARCH}" "${PY_FILE}"

      - name: 打包产物压缩（包含所有文件）
        run: |
          mkdir -p dist_upload
          # 将dist目录下所有以APP_NAME-ARCH开头的文件和目录全部打包
          cd dist
          zip -r "../dist_upload/${APP_NAME}-${{ matrix.arch }}.zip" "${APP_NAME}-${{ matrix.arch }}"*
          cd ..

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.APP_NAME }}-${{ matrix.arch }}"
          path: dist_upload/*.zip

  release:
    needs: build-macos
    runs-on: ubuntu-latest
    steps:
      - name: 下载所有构建产物
        uses: actions/download-artifact@v3
        with:
          path: all_dist

      - name: 展示产物
        run: ls -R all_dist

      - name: 上传到 GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: all_dist/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
