name: Build and Release Mac App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-intel:
    runs-on: macos-13
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Intel 版打包 .app
        run: |
          pyinstaller --noconfirm --windowed --name "Jeffern影视平台-intel" mac-web.py

      - name: 上传 dist 目录（Intel）
        uses: actions/upload-artifact@v4
        with:
          name: dist-intel
          path: dist

  build-arm:
    runs-on: macos-14
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: ARM 版打包 .app
        run: |
          pyinstaller --noconfirm --windowed --name "Jeffern影视平台-arm" mac-web.py

      - name: 上传 dist 目录（ARM）
        uses: actions/upload-artifact@v4
        with:
          name: dist-arm
          path: dist

  release:
    needs: [build-intel, build-arm]
    runs-on: ubuntu-latest
    steps:
      - name: 下载 Intel dist 目录
        uses: actions/download-artifact@v4
        with:
          name: dist-intel
          path: dist-intel

      - name: 下载 ARM dist 目录
        uses: actions/download-artifact@v4
        with:
          name: dist-arm
          path: dist-arm

      - name: 打包所有 dist 目录为 zip
        run: |
          zip -r Jeffern影视平台-intel-dist.zip dist-intel
          zip -r Jeffern影视平台-arm-dist.zip dist-arm

      - name: 发布 Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Jeffern影视平台-intel-dist.zip
            Jeffern影视平台-arm-dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
