name: Build and Release Mac App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-intel:
    runs-on: macos-13
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Intel 版打包
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "Jeffern影视平台-intel" mac-web.py

      - name: 打包为 zip（保留权限）
        run: |
          cd dist
          chmod +x Jeffern影视平台-intel
          zip Jeffern影视平台-intel-macos-x86_64.zip Jeffern影视平台-intel

      - name: 上传 Intel 产物
        uses: actions/upload-artifact@v4
        with:
          name: Jeffern影视平台-intel
          path: dist/Jeffern影视平台-intel-macos-x86_64.zip

  build-arm:
    runs-on: macos-14
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: ARM 版打包
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "Jeffern影视平台-arm" mac-web.py

      - name: 打包为 zip（保留权限）
        run: |
          cd dist
          chmod +x Jeffern影视平台-arm
          zip Jeffern影视平台-arm-macos-arm64.zip Jeffern影视平台-arm

      - name: 上传 ARM 产物
        uses: actions/upload-artifact@v4
        with:
          name: Jeffern影视平台-arm
          path: dist/Jeffern影视平台-arm-macos-arm64.zip

  release:
    needs: [build-intel, build-arm]
    runs-on: ubuntu-latest
    steps:
      - name: 下载 Intel 产物
        uses: actions/download-artifact@v4
        with:
          name: Jeffern影视平台-intel
          path: dist/

      - name: 下载 ARM 产物
        uses: actions/download-artifact@v4
        with:
          name: Jeffern影视平台-arm
          path: dist/

      - name: 发布 Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Jeffern影视平台-intel-macos-x86_64.zip
            dist/Jeffern影视平台-arm-macos-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
