name: Build macOS Universal App

on:
  push:
    tags:
      - 'v*'   # 推送 tag 时自动发布 Release
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build-intel:
    runs-on: macos-13  # Intel 架构
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pywebview pyinstaller

      - name: 打包 x86_64 应用
        run: |
          pyinstaller --onefile --windowed --name "Jeffern影视平台" mac-web.py

      - name: 上传 x86_64 产物
        uses: actions/upload-artifact@v4
        with:
          name: app-x86_64
          path: dist/Jeffern影视平台

  build-arm:
    runs-on: macos-14  # Apple Silicon (arm64)
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pywebview pyinstaller

      - name: 打包 arm64 应用
        run: |
          pyinstaller --onefile --windowed --name "Jeffern影视平台" mac-web.py

      - name: 上传 arm64 产物
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64
          path: dist/Jeffern影视平台

  merge-universal:
    needs: [build-intel, build-arm]
    runs-on: macos-14
    steps:
      - name: 下载 x86_64 产物
        uses: actions/download-artifact@v4
        with:
          name: app-x86_64
          path: x86_64

      - name: 下载 arm64 产物
        uses: actions/download-artifact@v4
        with:
          name: app-arm64
          path: arm64

      - name: 合并为 Universal 二进制
        run: |
          lipo -create -output Jeffern影视平台_universal x86_64/Jeffern影视平台 arm64/Jeffern影视平台
          file Jeffern影视平台_universal

      - name: 上传 Universal 产物
        uses: actions/upload-artifact@v4
        with:
          name: Jeffern影视平台-mac-universal
          path: Jeffern影视平台_universal

      - name: 自动发布 Release
        uses: softprops/action-gh-release@v2
        with:
          files: Jeffern影视平台_universal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
