name: Build macOS Universal .app

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build-intel:
    runs-on: macos-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Intel 版打包
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "Jeffern影视平台-intel" mac-web.py

      - name: 上传 Intel 产物
        uses: actions/upload-artifact@v4
        with:
          name: Jeffern影视平台-intel
          path: dist/Jeffern影视平台-intel

  build-arm:
    runs-on: macos-14
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: M 芯片版打包
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "Jeffern影视平台-arm" mac-web.py

      - name: 上传 ARM 产物
        uses: actions/upload-artifact@v4
        with:
          name: Jeffern影视平台-arm
          path: dist/Jeffern影视平台-arm

  release:
    needs: [build-intel, build-arm]
    runs-on: ubuntu-latest
    steps:
      - name: 下载 Intel 产物
        uses: actions/download-artifact@v4
        with:
          name: Jeffern影视平台-intel
          path: dist/

      - name: 下载 ARM 产物
        uses: actions/download-artifact@v4
        with:
          name: Jeffern影视平台-arm
          path: dist/

      - name: 发布 Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Jeffern影视平台-intel
            dist/Jeffern影视平台-arm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
